<?php

/**
 * BaseFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property clob $content
 * @property User $User
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method integer  getUserId()  Returns the current record's "user_id" value
 * @method string   getName()    Returns the current record's "name" value
 * @method clob     getContent() Returns the current record's "content" value
 * @method User     getUser()    Returns the current record's "User" value
 * @method Feedback setId()      Sets the current record's "id" value
 * @method Feedback setUserId()  Sets the current record's "user_id" value
 * @method Feedback setName()    Sets the current record's "name" value
 * @method Feedback setContent() Sets the current record's "content" value
 * @method Feedback setUser()    Sets the current record's "User" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeedback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feedback');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}