<?php

/**
 * BaseNewsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property clob $content
 * @property timestamp $publish_at
 * @property User $User
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getUserId()     Returns the current record's "user_id" value
 * @method string     getTitle()      Returns the current record's "title" value
 * @method clob       getContent()    Returns the current record's "content" value
 * @method timestamp  getPublishAt()  Returns the current record's "publish_at" value
 * @method User       getUser()       Returns the current record's "User" value
 * @method Newsletter setId()         Sets the current record's "id" value
 * @method Newsletter setUserId()     Sets the current record's "user_id" value
 * @method Newsletter setTitle()      Sets the current record's "title" value
 * @method Newsletter setContent()    Sets the current record's "content" value
 * @method Newsletter setPublishAt()  Sets the current record's "publish_at" value
 * @method Newsletter setUser()       Sets the current record's "User" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('publish_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}