<?php

/**
 * BaseNewsletterAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $admin_id
 * @property string $title
 * @property clob $content
 * @property timestamp $publish_date
 * @property Admin $Admin
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method integer         getAdminId()      Returns the current record's "admin_id" value
 * @method string          getTitle()        Returns the current record's "title" value
 * @method clob            getContent()      Returns the current record's "content" value
 * @method timestamp       getPublishDate()  Returns the current record's "publish_date" value
 * @method Admin           getAdmin()        Returns the current record's "Admin" value
 * @method NewsletterAdmin setId()           Sets the current record's "id" value
 * @method NewsletterAdmin setAdminId()      Sets the current record's "admin_id" value
 * @method NewsletterAdmin setTitle()        Sets the current record's "title" value
 * @method NewsletterAdmin setContent()      Sets the current record's "content" value
 * @method NewsletterAdmin setPublishDate()  Sets the current record's "publish_date" value
 * @method NewsletterAdmin setAdmin()        Sets the current record's "Admin" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletterAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_admin');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('admin_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('content', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65532,
             ));
        $this->hasColumn('publish_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin', array(
             'local' => 'admin_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}