<?php

/**
 * BaseNewsletterTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $teacher_id
 * @property string $title
 * @property clob $content
 * @property timestamp $publish_date
 * @property Teacher $Admin
 * 
 * @method integer           getId()           Returns the current record's "id" value
 * @method integer           getTeacherId()    Returns the current record's "teacher_id" value
 * @method string            getTitle()        Returns the current record's "title" value
 * @method clob              getContent()      Returns the current record's "content" value
 * @method timestamp         getPublishDate()  Returns the current record's "publish_date" value
 * @method Teacher           getAdmin()        Returns the current record's "Admin" value
 * @method NewsletterTeacher setId()           Sets the current record's "id" value
 * @method NewsletterTeacher setTeacherId()    Sets the current record's "teacher_id" value
 * @method NewsletterTeacher setTitle()        Sets the current record's "title" value
 * @method NewsletterTeacher setContent()      Sets the current record's "content" value
 * @method NewsletterTeacher setPublishDate()  Sets the current record's "publish_date" value
 * @method NewsletterTeacher setAdmin()        Sets the current record's "Admin" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletterTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_teacher');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('teacher_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('content', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65532,
             ));
        $this->hasColumn('publish_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teacher as Admin', array(
             'local' => 'teacher_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}