<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Topic', 'doctrine');

/**
 * BaseTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $pdf_filename
 * @property timestamp $publish_date
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method string    getTitle()        Returns the current record's "title" value
 * @method string    getPdfFilename()  Returns the current record's "pdf_filename" value
 * @method timestamp getPublishDate()  Returns the current record's "publish_date" value
 * @method Topic     setId()           Sets the current record's "id" value
 * @method Topic     setTitle()        Sets the current record's "title" value
 * @method Topic     setPdfFilename()  Sets the current record's "pdf_filename" value
 * @method Topic     setPublishDate()  Sets the current record's "publish_date" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('topic');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('pdf_filename', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('publish_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp(25)',
              'expression' => 'NOW()',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp(25)',
              'expression' => 'NOW()',
             ),
             ));
        $this->actAs($timestampable0);
    }
}