<?php

/**
 * BaseTeacherStudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $teacher_id
 * @property integer $student_id
 * @property Teacher $Teacher
 * @property Student $Student
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getTeacherId()  Returns the current record's "teacher_id" value
 * @method integer        getStudentId()  Returns the current record's "student_id" value
 * @method Teacher        getTeacher()    Returns the current record's "Teacher" value
 * @method Student        getStudent()    Returns the current record's "Student" value
 * @method TeacherStudent setId()         Sets the current record's "id" value
 * @method TeacherStudent setTeacherId()  Sets the current record's "teacher_id" value
 * @method TeacherStudent setStudentId()  Sets the current record's "student_id" value
 * @method TeacherStudent setTeacher()    Sets the current record's "Teacher" value
 * @method TeacherStudent setStudent()    Sets the current record's "Student" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeacherStudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher_student');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('teacher_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('student_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Student', array(
             'local' => 'student_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}