<?php

/**
 * BaseStudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $furigana
 * @property integer $zipcode
 * @property string $address
 * @property string $contact
 * @property User $User
 * @property Doctrine_Collection $TeacherStudent
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method string              getFurigana()       Returns the current record's "furigana" value
 * @method integer             getZipcode()        Returns the current record's "zipcode" value
 * @method string              getAddress()        Returns the current record's "address" value
 * @method string              getContact()        Returns the current record's "contact" value
 * @method User                getUser()           Returns the current record's "User" value
 * @method Doctrine_Collection getTeacherStudent() Returns the current record's "TeacherStudent" collection
 * @method Student             setId()             Sets the current record's "id" value
 * @method Student             setUserId()         Sets the current record's "user_id" value
 * @method Student             setFurigana()       Sets the current record's "furigana" value
 * @method Student             setZipcode()        Sets the current record's "zipcode" value
 * @method Student             setAddress()        Sets the current record's "address" value
 * @method Student             setContact()        Sets the current record's "contact" value
 * @method Student             setUser()           Sets the current record's "User" value
 * @method Student             setTeacherStudent() Sets the current record's "TeacherStudent" collection
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'unique' => true,
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('furigana', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('zipcode', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('address', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('contact', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('TeacherStudent', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}