<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $image1
 * @property string $image2
 * @property clob $body
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method string  getTitle()  Returns the current record's "title" value
 * @method string  getImage1() Returns the current record's "image1" value
 * @method string  getImage2() Returns the current record's "image2" value
 * @method clob    getBody()   Returns the current record's "body" value
 * @method Page    setId()     Sets the current record's "id" value
 * @method Page    setTitle()  Sets the current record's "title" value
 * @method Page    setImage1() Sets the current record's "image1" value
 * @method Page    setImage2() Sets the current record's "image2" value
 * @method Page    setBody()   Sets the current record's "body" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('id', 'integer', 1, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 1,
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('image1', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('image2', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('body', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65532,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}