<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubscriptionXTeacher', 'doctrine');

/**
 * BaseSubscriptionXTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subscription_id
 * @property integer $teacher_id
 * @property decimal $price
 * @property Subscription $Subscription
 * @property Teacher $Teacher
 * 
 * @method integer              getSubscriptionId()  Returns the current record's "subscription_id" value
 * @method integer              getTeacherId()       Returns the current record's "teacher_id" value
 * @method decimal              getPrice()           Returns the current record's "price" value
 * @method Subscription         getSubscription()    Returns the current record's "Subscription" value
 * @method Teacher              getTeacher()         Returns the current record's "Teacher" value
 * @method SubscriptionXTeacher setSubscriptionId()  Sets the current record's "subscription_id" value
 * @method SubscriptionXTeacher setTeacherId()       Sets the current record's "teacher_id" value
 * @method SubscriptionXTeacher setPrice()           Sets the current record's "price" value
 * @method SubscriptionXTeacher setSubscription()    Sets the current record's "Subscription" value
 * @method SubscriptionXTeacher setTeacher()         Sets the current record's "Teacher" value
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubscriptionXTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscription_x_teacher');
        $this->hasColumn('subscription_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('teacher_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('price', 'decimal', 9, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 9,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subscription', array(
             'local' => 'subscription_id',
             'foreign' => 'id'));

        $this->hasOne('Teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id'));
    }
}