<?php

/**
 * BaseTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $email
 * @property string $password
 * @property clob $portfolio
 * @property clob $details
 * @property Doctrine_Collection $Subscription
 * @property Doctrine_Collection $NewsletterTeacher
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getEmail()             Returns the current record's "email" value
 * @method string              getPassword()          Returns the current record's "password" value
 * @method clob                getPortfolio()         Returns the current record's "portfolio" value
 * @method clob                getDetails()           Returns the current record's "details" value
 * @method Doctrine_Collection getSubscription()      Returns the current record's "Subscription" collection
 * @method Doctrine_Collection getNewsletterTeacher() Returns the current record's "NewsletterTeacher" collection
 * @method Teacher             setId()                Sets the current record's "id" value
 * @method Teacher             setTitle()             Sets the current record's "title" value
 * @method Teacher             setEmail()             Sets the current record's "email" value
 * @method Teacher             setPassword()          Sets the current record's "password" value
 * @method Teacher             setPortfolio()         Sets the current record's "portfolio" value
 * @method Teacher             setDetails()           Sets the current record's "details" value
 * @method Teacher             setSubscription()      Sets the current record's "Subscription" collection
 * @method Teacher             setNewsletterTeacher() Sets the current record's "NewsletterTeacher" collection
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 80,
             ));
        $this->hasColumn('password', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('portfolio', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65532,
             ));
        $this->hasColumn('details', 'clob', 65532, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65532,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Subscription', array(
             'local' => 'id',
             'foreign' => 'teacher_id'));

        $this->hasMany('NewsletterTeacher', array(
             'local' => 'id',
             'foreign' => 'teacher_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}