<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SubscriptionPlan', 'doctrine');

/**
 * BaseSubscriptionPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $teacher_id
 * @property string $name
 * @property integer $duration
 * @property decimal $price
 * @property timestamp $updated_at
 * @property timestamp $created_at
 * @property Teacher $Teacher
 * @property Doctrine_Collection $Subscription
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getTeacherId()    Returns the current record's "teacher_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getDuration()     Returns the current record's "duration" value
 * @method decimal             getPrice()        Returns the current record's "price" value
 * @method timestamp           getUpdatedAt()    Returns the current record's "updated_at" value
 * @method timestamp           getCreatedAt()    Returns the current record's "created_at" value
 * @method Teacher             getTeacher()      Returns the current record's "Teacher" value
 * @method Doctrine_Collection getSubscription() Returns the current record's "Subscription" collection
 * @method SubscriptionPlan    setId()           Sets the current record's "id" value
 * @method SubscriptionPlan    setTeacherId()    Sets the current record's "teacher_id" value
 * @method SubscriptionPlan    setName()         Sets the current record's "name" value
 * @method SubscriptionPlan    setDuration()     Sets the current record's "duration" value
 * @method SubscriptionPlan    setPrice()        Sets the current record's "price" value
 * @method SubscriptionPlan    setUpdatedAt()    Sets the current record's "updated_at" value
 * @method SubscriptionPlan    setCreatedAt()    Sets the current record's "created_at" value
 * @method SubscriptionPlan    setTeacher()      Sets the current record's "Teacher" value
 * @method SubscriptionPlan    setSubscription() Sets the current record's "Subscription" collection
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubscriptionPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscription_plan');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('teacher_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('duration', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('price', 'decimal', 9, array(
             'type' => 'decimal',
             'unsigned' => true,
             'default' => '0.00',
             'notnull' => true,
             'length' => 9,
             'scale' => '2',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Teacher', array(
             'local' => 'teacher_id',
             'foreign' => 'id'));

        $this->hasMany('Subscription', array(
             'local' => 'id',
             'foreign' => 'subscription_plan_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created_at' => 
             array(
              'type' => 'timestamp(25)',
              'expression' => 'NOW()',
             ),
             'updated_at' => 
             array(
              'type' => 'timestamp(25)',
              'expression' => 'NOW()',
             ),
             ));
        $this->actAs($timestampable0);
    }
}