<?php

/**
 * AdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Admin');
    }
}