<?php

/**
 * NewsletterTeacherTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterTeacherTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterTeacherTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsletterTeacher');
    }
}