<?php

/**
 * NewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsletter');
    }
    
    public function getActiveNewsletters()
    {
         $q = $this->createQuery('n');
         return $q->execute();
    }
    
    public function getDeliveredNewsletters($id)
    {
         $q = $this->createQuery('n')
         ->where('n.teacher_id = ?', $id)
         ->addOrderBy('created_at ASC');
         
         return $q;
    }
   
}