<?php

/**
 * NewsletterAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsletterAdmin');
    }
}