<?php

/**
 * NewsletterXStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterXStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterXStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsletterXStudent');
    }
     public function getStudentNewsletters()
    {
        $student = 1;
        $q = $this->createQuery('x')
        ->leftJoin('x.Newsletter n')
        ->leftJoin('x.Student s')
       ->where('student_id = ?', $student);
      /* ->where('s.valid_until > ?', date('Y-m-d H:i:s', time()));*/
   
      return $q->execute();
    }
}