<?php

/**
 * NewsletterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsletter');
    }
    
    public function getActiveNewsletters()
    {
         $q = $this->createQuery('n');
         return $q->execute();
    }
    
    public function getDeliveredNewsletters($id)
    {
         $q = $this->createQuery('n')
         ->where('n.teacher_id = ?', $id)
         ->addOrderBy('created_at ASC');
         
         return $q;
    }
    
    public function getNewsletters($id)
    {
         $q = $this->createQuery('n')
        ->where('n.teacher_id = ?', $id)
        ->addOrderBy('created_at ASC');
        
        return $q;
    }
    /*get student's newsletter*/
     public function getStudentNewsletters($id)
    {
        $q = $this->createQuery('n')
        ->leftJoin('n.NewsletterXStudent nx')
        ->leftJoin('nx.Student stud')
        ->where('stud.id = ?', $id);
   
      return $q->execute();
   }
   
   /*get teacher's newsletter*/
	  public function getTeacherNewsletters()
    {
        $q = $this->createQuery('n')
        ->leftJoin('n.Teacher t');
         
      return $q->execute();
    }
    
    /*get student's teachers*/
	  public function getStudentTeachers($id)
    {
        $q = $this->createQuery('n')
        ->leftJoin('n.NewsletterXStudent nx')
        ->leftJoin('n.Teacher t')
        ->where('nx.student_id = ?', $id);
         
      return $q->execute();
    } 
   
}