<?php

/**
 * NewsletterXStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterXStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterXStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsletterXStudent');
    }
    public function getStudentNewsletters()
     {
       $student = 1;
       $q = $this->createQuery('a')
       ->leftJoin('a.Newsletter n')
       ->leftJoin('a.Student s')
         ->where('a.student_id = ?', $student);
    
       return $q->execute();
     }
}