<?php

/**
 * NewsletterXStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsletterXStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsletterXStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsletterXStudent');
    }
    
     public function getStudentNewsletters($id)
    {
        $q = $this->createQuery('x')
        ->leftJoin('x.Newsletter n')
        ->where('x.student_id = ?', $id);
   
      return $q->execute();
    }
}