<?php

/**
 * Settlement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Settlement extends BaseSettlement
{
  /**
   * Returns the string representation for the status property.
   *
   * @return string
   */
  public function _getStatus()
  {
    switch ($this->getStatus())
    {
      case 0: return 'Waiting';
      case 1: return 'Paid';
      case 1: return 'Cancelled';
      case 1: return 'Declined';
    }
  }
}