<?php

/**
 * SettlementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SettlementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SettlementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Settlement');
    }
}