<?php

/**
 * StudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object StudentTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Student');
  }
  
  /**
   * Query for retreiving Students with active and valid subscription to the given Teacher.
   *
   * @param int   $teacherId Id of Teacher that the Student should be subscribed to.
   * @param mixed $options   Optional. Defaults to empty array. Possible values: 'name', 'email'.
   * @param int   $limit     Optional. Defaults to 0. Limit to query.
   * @param int   $offset    Optional. Defaults to 0. Offset to query.
   * @return Doctrine_Query Query for retrieving Students.
   */
  public function getSubscribedToTeacherQuery($teacherId, $options = array(), $limit = 0, $offset = 0)
  {
    $q = $this->createQuery('stu')
          ->innerJoin('stu.Subscription sub')
          ->innerJoin('sub.SubscriptionPlan sbp')
          ->where('sbp.teacher_id = ?', $teacherId)
          ->andWhere('sub.is_active = ?', 1) // active subscription
          ->andWhere('sub.valid_until >= NOW()'); // valid subscription
    
    if (0 < count($options))
    {
      if (array_key_exists('name', $options) && ('' != $options['name']))
      {
        $q->andWhere('stu.name LIKE ?', '%' . $options['name'] . '%');
      }
      if (array_key_exists('email', $options) && ('' != $options['email']))
      {
        $q->andWhere('stu.email LIKE ?', '%' . $options['email'] . '%');
      }
    }
    
    if (0 < $limit)
    {
      $q->limit($limit);
    }
    
    if (0 < $offset)
    {
      $q->offset($offset);
    }
    
    return $q;
  }
}