<?php

/**
 * StudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Student');
    }
    
    public function getStudentNewsletter()
    {
        $student = 1;
        $q = $this->createQuery('s')
        ->leftJoin('s.NewsletterXStudent x')
        ->leftJoin('x.Newsletter n')
       ->where('student_id = ?', $student);
      /* ->where('s.valid_until > ?', date('Y-m-d H:i:s', time()));*/
   
      return $q->execute();
    }
    
}