<?php

/**
 * Subscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Subscription extends BaseSubscription
{
  /**
   * Returns the string representation for the is_active property.
   *
   * @return string
   */
  public function _getIsActive()
  {
    switch ($this->getIsActive())
    {
      case 0: return 'Inactive';
      case 1: return 'Active';
    }
  }
}