<?php

/**
 * SubscriptionPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubscriptionPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubscriptionPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubscriptionPlan');
    }
}