<?php

/**
 * TeacherStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeacherStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeacherStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeacherStudent');
    }
}