<?php

/**
 * Teacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    DOUBLECLICK
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Teacher extends BaseTeacher
{
  /**
   * Gets Students that have active and valid subscription to this Teacher.
   *
   * @see StudentTable::getSubscribedToTeacher()
   * @param int $limit  Optional. Defaults to 0. Limit to query.
   * @param int $offset Optional. Defaults to 0. Offset to query.
   * @return Doctrine_Collection Collection of Students.
   */
  public function getSubscribedStudents($limit = 0, $offset = 0)
  {
    return StudentTable::getInstance()->getSubscribedToTeacherQuery($this->getId(), $limit, $offset)->execute();
  }
}
