<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }
    public function getActiveNewsletter()
    {
       $q = $this->createQuery('n')
        ->leftJoin('n.NewsletterXStudent x')
        ->leftJoin('n.Subscription s')
        ->where('s.valid_until > ?', date('Y-m-d H:i:s', time()));
   
      return $q->execute();
    }
}
