# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

home:
  url:   /
  param: { module: home, action: index }
  
subscription-add:
  url: /subscription/add
  param: { module: subscription, action: add }
  
student-subscriptions:
  url: /subscriptions-list
  param: { module: student, action: subscriptionsList }
    
teacher-account-settings:
  url:   /teacher/account-settings
  param:   { module: teacher, action: accountSettings }

teacher-account-settings-confirm:
  url: /teacher/account-settings/confirm
  param: { module: teacher, action: confirm }
  
teacher-students:
  url: /teacher/students-list
  param: { module: teacher, action: studentsList }

teacher-introduction:
  url: /teacher/introduction
  param: { module: dynamic, action: teacherIntroduction }

teacher-portfolio:
  url:   /teacher/portfolio
  class:   sfDoctrineRoute
  options: { model: Teacher, type: object }
  param:   { module: teacher, action: portfolio }
  requirements:
    id: \d+
    sf_method: [get]

teacher-details:
  url: /teacher/details
  param: { module: teacher, action: teacherDetails }

dashboard:
  url:   /dashboard
  param: { module: student, action: dashboard }

logout:
  url: /logout
  param: { module: auth, action: logout }

login:
  url: /login/:userType
  param: { userType: "", module: auth, action: login }

change-password:
  url: /change-password/:userType
  param: { userType: "", module: auth, action: changePassword }

remind-password:
  url: /remind-password/:userType
  param: { userType: "", module: auth, action: remindPassword }

register-message:
  url: /register/message
  param: { module: static, action: registrationMessage }

register-activate:
  url: /register/activate
  param: { module: register, action: activate }

register-confirm:
  url: /register/confirm
  param: { module: register, action: confirm }

register:
  url: /register
  param: { module: register, action: index }

contact:
  url: /contact
  param: { module: contact, action: index }

contact-confirm:
  url: /contact/confirm
  param: { module: contact, action: confirm }

dashboard-newsletter:
  url:   /newsletter/:id  
  class:   sfDoctrineRoute
  options: { model: Newsletter, type: object }
  param:   { module: student, action: show }
  requirements:
    id: \d+
    sf_method: [get]

dashboard-teacher-newsletter:
  url:   /teacher/:id  
  class:   sfDoctrineRoute
  options: { model: Newsletter, type: object }
  param:   { module: student, action: list }
  requirements:
    id: \d+

delivered-newsletters:
  url: /delivered-newsletters
  param: { module: newsletter, action: index }
  
delivered-newsletter-detail:
  url:   /delivered-newsletter/:id  
  class:   sfDoctrineRoute
  options: { model: Newsletter, type: object }
  param:   { module: newsletter, action: show }
  requirements:
    id: \d+

new-newsletter:
  url:   /new-newsletter
  param:   { module: newsletter, action: new }

newsletter-confirm:
  url: /newsletter/confirm
  param: { module: newsletter, action: confirm }

new-newsletter-message:
  url: /new-newsletter/message
  param: { module: static, action: newsletterMessage }

feedback:
  url: /feedback
  param: { module: dynamic, action: feedback }

page1:
  url: /page1
  param: { module: page, action: page1 }
  
page2:
  url: /page2
  param: { module: page, action: page2 }

page3:
  url: /page3
  param: { module: page, action: page3 }

page4:
  url: /page4
  param: { module: page, action: page4 }

page5:
  url: /page5
  param: { module: page, action: page5 }

page6:
  url: /page6
  param: { module: page, action: page6 }
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
