# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

home:
  url:   /
  param: { module: home, action: index }
    
teacher-account-settings:
  url:   /teacher/account-settings
  param:   { module: teacher, action: edit }

teacher-account-settings-confirm:
  url: /teacher/account-settings/confirm
  param: { module: teacher, action: confirm }
  
teacher-students:
  url: /teacher/students-list
  param: { module: teacher, action: studentsList }
  
dashboard:
  url:   /dashboard
  param: { module: student, action: dashboard }
  
logout:
  url: /logout
  param: { module: auth, action: logout }
  
login:
  url: /login/:userType
  param: { userType: "", module: auth, action: login }
  
change-password:
  url: /change-password/:userType
  param: { userType: "", module: auth, action: changePassword }
  
remind-password:
  url: /remind-password/:userType
  param: { userType: "", module: auth, action: remindPassword }
  
register-message:
  url: /register/message
  param: { module: static, action: registrationMessage }
  
register-activate:
  url: /register/activate
  param: { module: register, action: activate }
  
register-confirm:
  url: /register/confirm
  param: { module: register, action: confirm }

register:
  url: /register
  param: { module: register, action: index }

dashboard-newsletter:
  url:   /newsletter/:id  
  class:   sfDoctrineRoute
  options: { model: Newsletter, type: object }
  param:   { module: student, action: show }
  requirements:
    id: \d+
    sf_method: [get]
    
dashboard-teacher-newsletter:
  url:   /teacher/:id  
  class:   sfDoctrineRoute
  options: { model: Newsletter, type: object }
  param:   { module: student, action: list }
  requirements:
    id: \d+

<<<<<<< Updated upstream
delivered-newsletters:
  url: /delivered-newsletters
  param: { module: newsletter, action: index }

new-newsletter:
  url: /new-newsletter
  param: { module: newsletter, action: new }
  
delivered-newsletter-detail:
  url:   /delivered-newsletter/:id  
=======
delivered-newsletter-list:
  url: /delivered-newsletter
  param: { module: newsletter, action: index }
  
delivered-newsletter:
  url:   /delivered-newsletter/id/:id  
>>>>>>> Stashed changes
  class:   sfDoctrineRoute
  options: { model: Newsletter, type: object }
  param:   { module: newsletter, action: show }
  requirements:
    id: \d+
<<<<<<< Updated upstream
  
=======
    sf_method: [get]
    
>>>>>>> Stashed changes
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
