# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title:        DoubleClick
    language:     jp
    #description:  symfony project
    #keywords:     symfony, project
    #robots:       index, follow

  stylesheets:    [style.css,"ckeditor/_samples/sample.css"]
  javascripts:    ["ckeditor/ckeditor.js","ckeditor/_samples/sample.js"]
  has_layout:     true
  layout:         layout
