all:
  envi: %SF_ENVIRONMENT%
  
  system:
    salt: wi47m86vvmlahmtl86d5
    
  student_search:
    limit: 1

  delivered_newsletters:
    limit: 1
    
  contact:
    email: admin@doubleclick.co.jp
    name: Admin
    subject:  Inquiry
  
  mailmagazine:
    email: admin@doubleclick.co.jp
    name: Admin
    
  topic:
    upload_dir: %SF_UPLOAD_DIR%\topics
