all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=sf_doubleclick';
      username: root
      password: 
      encoding: utf8
      attributes:
        use_native_enum: true