all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=sf_doubleclick; unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock'
      username: root
      password: root
      encoding: utf8
      attributes:
        use_native_enum: true