Admin:
  connection: doctrine
  tableName: admin
  actAs:
    Timestampable:
      created_at: { type: timestamp(25), expression: 'NOW()' }
      updated_at: { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:           { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    name:         { type: string(100), notnull: true }
    email:        { type: string(80), notnull: true }
    password:     { type: string(50), notnull: true }
    updated_at:   { type: timestamp(25), notnull: false }
    created_at:   { type: timestamp(25), notnull: false }

City:
  connection: doctrine
  tableName: city
  columns:
    id:       { type: integer(2), unsigned: true, primary: true, autoincrement: true }
    state_id: { type: integer(2), unsigned: true, notnull: true, autoincrement: false }
    name:     { type: string(50), notnull: true }
  relations:
    State:    { local: state_id, foreign: id, type: one }
    Student:  { local: id, foreign: city_id, type: many }

Feedback:
  connection: doctrine
  tableName: feedback
  actAs:
    Timestampable:
      created_at:  { type: timestamp(25), expression: 'NOW()' }
      updated_at:  { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:            { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    customer_name: { type: string(80), notnull: true }
    body:          { type: blob(), notnull: false }
    publish_date:  { type: timestamp(25), notnull: true }
    updated_at:    { type: timestamp(25), notnull: false }
    created_at:    { type: timestamp(25), notnull: false }

Mailmagazine:
  connection: doctrine
  tableName: mailmagazine
  actAs:
    Timestampable:
      created_at: { type: timestamp(25), expre, expression: 'NOW()' }
      updated_at: { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:           { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    title:        { type: string(150), notnull: true }
    content:      { type: string(), notnull: false }
    publish_date: { type: timestamp(25), notnull: true }
    updated_at:   { type: timestamp(25), notnull: false }
    created_at:   { type: timestamp(25), notnull: false }

Newsletter:
  connection: doctrine
  tableName: newsletter
  actAs:
    Timestampable:
      created_at:       { type: timestamp(25), expression: 'NOW()' }
      updated_at:       { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:                 { type: integer(8), unsigned: true, primary: true, autoincrement: true }
    teacher_id:         { type: integer(8), unsigned: true, notnull: true }
    title:              { type: string(150), notnull: true }
    content:            { type: blob(), notnull: false }
    publish_date:       { type: timestamp(25), notnull: true }
    updated_at:         { type: timestamp(25), notnull: false }
    created_at:         { type: timestamp(25), notnull: false }
  relations:
    Teacher:            { local: teacher_id, foreign: id, type: one }
    NewsletterXStudent: { local: id, foreign: newsletter_id, type: many }

NewsletterXStudent:
  connection: doctrine
  tableName: newsletter_x_student
  columns:
    newsletter_id: { type: integer(8), unsigned: true, primary: true }
    student_id:    { type: integer(8), unsigned: true, primary: true }
  relations:
    Newsletter:    { local: newsletter_id, foreign: id, type: one }
    Student:       { local: student_id, foreign: id, type: one }

Page:
  connection: doctrine
  tableName: page
  actAs:
    Timestampable:
      created_at: { type: timestamp(25), expression: 'NOW()' }
      updated_at: { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:          { type: integer(1), unsigned: true, primary: true, autoincrement: true }
    title:       { type: string(150), notnull: true }
    image1:      { type: string(100), notnull: false }
    image2:      { type: string(100), notnull: false }
    body:        { type: blob(), notnull: false }
    updated_at:  { type: timestamp(25), notnull: false }
    created_at:  { type: timestamp(25), notnull: false }

Settlement:
  connection: doctrine
  tableName: settlement
  actAs:
    Timestampable:
      created_at: { type: timestamp(25), expression: 'NOW()' }
      updated_at: { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:           { type: integer(8), unsigned: true, primary: true, autoincrement: true }
    status:       { type: enum(1), values: [ '0', '1', '2', '3' ], default: '0', notnull: true }
    price:        { type: 'decimal(9, 2)', unsigned: true, default: '0.00', notnull: true }
    paid_at:      { type: timestamp(25), notnull: false }
    updated_at:   { type: timestamp(25), notnull: false }
    created_at:   { type: timestamp(25), notnull: false }
  relations:
    Subscription: { local: id, foreign: settlement_id, type: many }

State:
  connection: doctrine
  tableName: state
  columns:
    id:      { type: integer(2), unsigned: true, primary: true, autoincrement: true }
    name:    { type: string(50), notnull: true }
  relations:
    City:    { local: id, foreign: state_id, type: many }
    Student: { local: id, foreign: state_id, type: many }

Student:
  connection: doctrine
  tableName: student
  actAs:
    Timestampable:
      created_at:       { type: timestamp(25), expression: 'NOW()' }
      updated_at:       { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:                 { type: integer(8), unsigned: true, primary: true, autoincrement: true }
    name:               { type: string(100), notnull: true }
    furigana:           { type: string(100), notnull: false }
    email:              { type: string(80), notnull: true }
    password:           { type: string(50), notnull: false }
    status:             { type: enum(1), values: [ '0', '1', '2', '3', '4' ], default: '0', notnull: true }
    login_type:         { type: enum(1), values: [ '0', '1' ], default: '0', notnull: true }
    zipcode1:           { type: string(3), notnull: false }
    zipcode2:           { type: string(4), notnull: false }
    state_id:           { type: integer(2), unsigned: true, notnull: true }
    city_id:            { type: integer(2), unsigned: true, notnull: false }
    address:            { type: string(150), notnull: false }
    contact:            { type: string(20), notnull: false }
    picture:            { type: string(42), notnull: false }
    activation:         { type: string(255), notnull: false }
    updated_at:         { type: timestamp(25), notnull: false }
    created_at:         { type: timestamp(25), notnull: false }
  relations:
    City:               { local: city_id, foreign: id, type: one }
    State:              { local: state_id, foreign: id, type: one }
    NewsletterXStudent: { local: id, foreign: student_id, type: many }
    Subscription:       { local: id, foreign: student_id, type: many }

Subscription:
  connection: doctrine
  tableName: subscription
  actAs:
    Timestampable:
      created_at:         { type: timestamp(25), expression: 'NOW()' }
      updated_at:         { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:                   { type: integer(8), unsigned: true, primary: true, autoincrement: true }
    student_id:           { type: integer(8), unsigned: true, notnull: true }
    subscription_plan_id: { type: integer(4), unsigned: true, notnull: true }
    settlement_id:        { type: integer(8), unsigned: true, notnull: true }
    is_active:            { type: integer(1), default: '0', notnull: true }
    valid_until:          { type: timestamp(25), notnull: false }
    updated_at:           { type: timestamp(25), notnull: false }
    created_at:           { type: timestamp(25), notnull: false }
  relations:
    Student:              { local: student_id, foreign: id, type: one }
    Settlement:           { local: settlement_id, foreign: id, type: one }
    SubscriptionPlan:     { local: subscription_plan_id, foreign: id, type: one }

SubscriptionPlan:
  connection: doctrine
  tableName: subscription_plan
  actAs:
    Timestampable:
      created_at: { type: timestamp(25), expression: 'NOW()' }
      updated_at: { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:           { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    teacher_id:   { type: integer(8), unsigned: true, notnull: true }
    name:         { type: string(255), notnull: true }
    duration:     { type: integer(1), default: '0', notnull: true }
    price:        { type: 'decimal(9, 2)', unsigned: true, default: '0.00', notnull: true }
    updated_at:   { type: timestamp(25), notnull: false }
    created_at:   { type: timestamp(25), notnull: false }
  relations:
    Teacher:      { local: teacher_id, foreign: id, type: one }
    Subscription: { local: id, foreign: subscription_plan_id, type: many }

Teacher:
  connection: doctrine
  tableName: teacher
  actAs:
    Timestampable:
      created_at:     { type: timestamp(25), expression: 'NOW()' }
      updated_at:     { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:               { type: integer(8), unsigned: true, primary: true, autoincrement: true }
    title:            { type: string(100), notnull: true }
    email:            { type: string(80), notnull: true }
    password:         { type: string(50), notnull: true }
    sender_email:     { type: string(80), notnull: true }
    portfolio:        { type: string(), notnull: false }
    details:          { type: string(), notnull: false }
    picture:          { type: string(42), notnull: false }
    change_password:  { type: string(255), notnull: false }
    updated_at:       { type: timestamp(25), notnull: false }
    created_at:       { type: timestamp(25), notnull: false }
  relations:
    Newsletter:       { local: id, foreign: teacher_id, type: many }
    SubscriptionPlan: { local: id, foreign: teacher_id, type: many }

Topic:
  connection: doctrine
  tableName: topic
  actAs:
    Timestampable:
      created_at: { type: timestamp(25), expression: 'NOW()' }
      updated_at: { type: timestamp(25), expression: 'NOW()' }
  columns:
    id:           { type: integer(4), unsigned: true, primary: true, autoincrement: true }
    title:        { type: string(255), notnull: true }
    pdf_filename: { type: string(50), notnull: true }
    publish_date: { type: timestamp(25), notnull: true }
    updated_at:   { type: timestamp(25), notnull: false }
    created_at:   { type: timestamp(25), notnull: false }
