Admin:
  connection: doctrine
  tableName: admin
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
City:
  connection: doctrine
  tableName: city
  columns:
    id:
      type: integer(2)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    state_id:
      type: integer(2)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    State:
      local: state_id
      foreign: id
      type: one
    Student:
      local: id
      foreign: city_id
      type: many
Feedback:
  connection: doctrine
  tableName: feedback
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    customer_name:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    body:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    publish_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Page:
  connection: doctrine
  tableName: page
  columns:
    id:
      type: integer(1)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    title:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image1:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    image2:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    body:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Settlement:
  connection: doctrine
  tableName: settlement
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    paid_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Subscription:
      local: id
      foreign: settlement_id
      type: many
State:
  connection: doctrine
  tableName: state
  columns:
    id:
      type: integer(2)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    City:
      local: id
      foreign: state_id
      type: many
    Student:
      local: id
      foreign: state_id
      type: many
Student:
  connection: doctrine
  tableName: student
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    furigana:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    login_type:
      type: enum(1)
      fixed: false
      unsigned: false
      values:
        - '0'
        - '1'
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    zipcode1:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    zipcode2:
      type: string(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    address:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    state_id:
      type: integer(2)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    city_id:
      type: integer(2)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    contact:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    picture:
      type: string(42)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    status:
      type: enum(1)
      fixed: false
      unsigned: false
      values:
        - '0'
        - '1'
        - '2'
        - '3'
        - '4'
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    activation:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    City:
      local: city_id
      foreign: id
      type: one
    State:
      local: state_id
      foreign: id
      type: one
    Subscription:
      local: id
      foreign: student_id
      type: many
Subscription:
  connection: doctrine
  tableName: subscription
  columns:
    teacher_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    student_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    settlement_id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    status:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
    duration:
      type: enum(1)
      fixed: false
      unsigned: false
      values:
        - '0'
        - '1'
        - '2'
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    price:
      type: 'decimal(9, 2)'
      fixed: false
      unsigned: true
      primary: false
      default: '0.00'
      notnull: true
      autoincrement: false
    valid_until:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    modified_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Teacher:
      local: teacher_id
      foreign: id
      type: one
    Settlement:
      local: settlement_id
      foreign: id
      type: one
    Student:
      local: student_id
      foreign: id
      type: one
Teacher:
  connection: doctrine
  tableName: teacher
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    title:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(80)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    portfolio:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    details:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Subscription:
      local: id
      foreign: teacher_id
      type: many
Topic:
  connection: doctrine
  tableName: topic
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    title:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    pdf_filename:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    publish_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
